name: Bug Report
description: Report a bug in the RAG Financial Insights application
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the application is affected?
      options:
        - Financial Analyzer
        - Streamlit UI
        - FastAPI API
        - RAG / Search / Embeddings
        - Graph Store (Neo4j)
        - Docker / Infrastructure
        - CI/CD / GitHub Actions
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Upload file '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Error Output
      description: Paste any relevant logs or error messages.
      render: shell

  - type: dropdown
    id: python-version
    attributes:
      label: Python Version
      options:
        - "3.11"
        - "3.12"
        - "3.13"

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - Docker (docker compose up)
        - Local (streamlit run)
        - FastAPI standalone
        - CI/CD (GitHub Actions)
